name: Alternative actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            nvm install node
            cd /root/ci-cd-next
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npm run build
            rm -r ../../var/www/dist/
            rm -r ../../var/www/.next/
            mv .next/ ../../var/www/
            sudo service nginx restart